### ISSUE TITLE
Ansible failure

### ISSUE THREAD

**Issue by soaErikNord** [ForgeRock/frstack#11]
Sorry, new to this whole vagrant and ansible stuff, but keep getting further with every step.  And completely understand work in progress.

I did to a pull of your latest updates.  `vagrant destroy` , `vagrant up`

```
TASK: [opendj | No staged archive found. Downloading] *************************
fatal: [oisserver] => failed to parse: SUDO-SUCCESS-ozirdncbbhlfsugivszzghiysiheyoqg
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425656149.27-20481716404660/get_url", line 2072, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425656149.27-20481716404660/get_url", line 222, in main
    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425656149.27-20481716404660/get_url", line 146, in url_get
    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425656149.27-20481716404660/get_url", line 2060, in fetch_url
    r = urllib2.urlopen(request, None, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/usr/lib64/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: OpenDJ-2.6.2.zip


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/enord/frstack.retry

oisserver                  : ok=73   changed=54   unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by wstrange** [comment]
It looks like it is trying to pull down  2.6.2 - which is not on the .org
site.

Which "release" variable are you trying to use?

If you use the "nightly" ( edit the global_vars/all) it should try to pull
down nightly builds

Alternatively - download all the products into staging/, and edit your own
custom.yml file to match those versions (see staging.yml as an example)

Downloading the right bits is the tricky part to automate. I do need to
find a better more robust way of doing this....

**Comment by soaErikNord** [comment]
Thanks, updated version numbers in staged.yaml in ansible/vars and everything installed properly.  I can connect to everything successfully.

**Comment by wstrange** [comment]
Great - glad to see you got it working. 


This is definitely harder than it should be.    Pull requests welcome!
